# Fichier Character.py
ENROLL_CHARACTER_GREED = -1
FIRE_CHARACTER_GREED = 1
REFUSEQUESTREQUEST_GIVER_GREED = -1

# Fichier Organisation.py
DOINGQUEST_WIN_GIVER_GREED = 1
DOINGQUEST_WIN_TEAM_GREED = 1
DOINGQUEST_FAIL_GIVER_GREED = -1
DOINGQUEST_FAIL_TEAM_GREED = -1